client/package.json
docker-compose.yml
server/package.json

Make sure to delete the node_modules folders as they get mounted in the docker image and cause conflicts.

Fixed docker-compose and npm install order

---

client/src/app/menu/menu.component.html
client/src/app/menu/menu.component.ts

Add minimum resolution warning

---

server/src/helpers/game/commands/gm/GMAllegiance.ts
server/src/helpers/game/commands/gm/index.ts

Ported over the GMAllegiance command from LOTR1. 

Add GMAllegiance command

---

server/src/helpers/character/PlayerHelper.ts
server/src/helpers/game/commands/gm/gainskill.ts
server/src/helpers/game/commands/gm/index.ts

A few test cases shown. Skill is increased/decreased as expected. Minimum of zero is enforced by gainSkill, and if gainSkill fails we show the error message to the GM

Gm commands gm gain skill

---

server/src/actions/auth/login.ts

Fixes saving when logging into an already logged in account

Fix login when already logged in

---

server/src/helpers/character/DirectionHelper.ts
server/src/helpers/character/InteractionHelper.ts

When a character tries to open a door, checks the distance between the character, and the door.

Add range check to try open door

---

server/scripts/setup.js

Adds unsafe-perm to make the setup run the same as the docker file

Add the unsafe-perm to match the docker file

---

client/src/app/containers/game-container/map/map.component.ts
client/src/app/containers/game-container/map/phasergame.ts
client/src/app/containers/game-container/map/phaserstates/logic.ts
client/src/app/containers/game-container/map/phaserstates/preload.ts
client/src/polyfills.ts

Fixes the intellisense in the client for Phaser.

Fix phaser intellisense

---

client/src/app/containers/game-container/map/map.component.ts
client/src/app/containers/game-container/map/phasergame.ts
client/src/app/containers/game-container/map/phaserstates/logic.ts
client/src/app/containers/game-container/map/phaserstates/preload.ts
client/src/app/pipelines/OutlinePipeline.ts

Outline's selected targets on the map

Outline targets

---

client/src/app/_shared/modals/options/options.component.ts
client/src/app/containers/lobby-container/char-select/char-select.component.ts
client/src/app/login/login.component.ts
client/src/app/services/options.service.ts
client/src/stores/settings.state.ts
shared/interfaces/settings.ts

Implements:
https://github.com/LandOfTheRair/LandOfTheRair/issues/99
1. Adds an option to auto join
2. When you login, if the auto join is on, it will skip the lobby,  and then join the game using the last slot used.

Add option to auto login to last used character

---

server/src/helpers/game/PlayerManager.ts
server/src/helpers/lobby/LobbyManager.ts

Removes removePlayerFromGameByAccount, and uses removePlayerFromGame

Use other remove player method

---

server/src/helpers/game/commands/basic/break.ts

1. Reduced duplication
2. Use armor hit sound when successfully breaking an item
3. Recalculate stats after removing the item, other methods seem to do this, so I added it here
4. Add the item name to the destroy message
5. Added more information when you fail to use the command properly

Refactor break

---

server/src/helpers/game/effects/player/Drowning.ts

Raises the minimum amount of damage taken from drowning over time.

Drowning hurts more over time

---

client/src/app/containers/game-container/map/map.component.ts
client/src/app/containers/game-container/map/phaserstates/logic.ts
client/src/app/pipelines/OutlinePipeline.ts

Uses a shader to simulate swimming

Use shader for swimming

---

client/src/app/containers/game-container/map/map.component.ts
client/src/app/containers/game-container/map/phaserstates/logic.ts
client/src/app/pipelines/GrayPostFXPipeline.ts

Implements https://github.com/LandOfTheRair/LandOfTheRair/issues/66

Make screen gray when you die

---

client/src/app/containers/game-container/map/phaserstates/logic.ts

Should fix https://github.com/LandOfTheRair/LandOfTheRair/issues/73

Fix drawing coins on the ground

---

server/src/helpers/game/commands/gm/eval.ts
server/src/helpers/game/commands/gm/index.ts

Adds a command to eval for GM debugging.
Ex usage: @eval user('Wrexbe').name

Add eval GM command

---

server/src/core/networking.ts

Add a message to console, when connections can actually be made

Report when connections can actually be accepted

---

server/src/helpers/core/Game.ts
server/src/helpers/data/GroundManager.ts
server/src/helpers/game/spells/utility/Vortex.ts
server/src/models/world/MapState.ts

1. Refactored Ground Manager
2. Stop sending empty grounds to clients.

Clean GroundManager, don't send empty stuff to client

---

server/src/helpers/character/DamageHelperPhysical.ts

50% damage bonus, before:
50% damage bonus, after:
Code is currently flooring the modifier, so unless you have 100% damage bonus you won't see any improvement from the traits/gear that adds 5-10%.

Floor modified damage, not damage modifier

---

client/scripts/prebuild-assets-all.js
client/src/app/services/asset.service.ts

Makes images look better.
Fixes color of walls next to door frames.

Use lossless webp

---

client/src/app/containers/game-container/map/phaserstates/preload.ts

Improves loading performance by... a lot.

phaser doesn't need to load the audio

---

server/src/helpers/character/CombatHelper.ts

Same fix as for physical damage, but for healing this time

Move floor command for healing as well

---

server/src/helpers/game/commands/gm/eval.ts

- Make @eval print, @exec not print, and @evalj, print as json
- Make the game variable directly usable

Make eval more user friendly

---

client/src/stores/account.state.ts
server/src/actions/auth/login.ts
server/src/actions/auth/logout.ts
server/src/actions/auth/register.ts
server/src/actions/game/command.ts
server/src/actions/lobby/play.ts
server/src/actions/lobby/quit.ts
server/src/actions/mod/Announce.ts
server/src/actions/mod/BlockGameAndKickAll.ts
server/src/actions/mod/SetMOTD.ts
server/src/actions/premium/silver.ts
server/src/helpers/lobby/DiscordHelper.ts
server/src/helpers/lobby/LobbyManager.ts
server/src/helpers/lobby/lobby-commands/kick.ts
shared/interfaces/account.ts

1. Fixes #160 
2. Avoids sending full accounts over the network
3. Adds more safety to logging out
4. Reduced dependence on account
5. Made duplicate users in the lobby list impossible on the server
6. Renamed methods, and moved them around to make it more obvious what they do.

refactor lobby code + fixes [NO MERGE]

---

server/src/helpers/core/db/CharacterDB.ts

Fix daily quests

---

server/src/helpers/game/spells/utility/Fate.ts

currently can't gain exp with fate

Stop blocking Exp gain on maps that allow Exp gain

---

server/src/helpers/game/tools/LootHelper.ts

Current code is checking how many items to drop, then if that number is over zero dropping one item. This makes mobs respect their minimum drops.

Choose min drops

---

client/src/app/containers/game-container/map/phaserstates/logic.ts

Improves the map's handling of being restarted. Clears out more data, doesn't register the events again, and refreshes the items.

Improve phaser map switching

---

client/package-lock.json
client/package.json
client/src/app/_shared/modals/newspells/newspells.component.ts
client/src/stores/macros.state.ts
server/package-lock.json
server/package.json
server/src/helpers/character/CharacterHelper.ts
server/src/helpers/character/DeathHelper.ts
server/src/helpers/character/ItemHelper.ts
server/src/helpers/character/StealHelper.ts
server/src/helpers/core/Database.ts
server/src/helpers/data/GroundManager.ts
server/src/helpers/data/ItemCreator.ts
server/src/helpers/data/NPCCreator.ts
server/src/helpers/game/commands/skills/creatures/npc/skillsuckmedium.ts
server/src/helpers/game/commands/skills/creatures/npc/skillsuckstrong.ts
server/src/helpers/game/commands/skills/creatures/npc/skillsuckweak.ts
server/src/helpers/game/effects/bottle/PermanentSkill.ts
server/src/helpers/game/effects/spell/song/DeadlyDirgeSong.ts
server/src/helpers/game/effects/spell/song/TranquilTrillSong.ts
server/src/helpers/game/spells/utility/Dispel.ts
server/src/models/world/Spawner.ts
server/src/models/world/ai/behaviors/crier.ts
server/src/models/world/ai/behaviors/identifier.ts
server/src/models/world/ai/behaviors/peddler.ts
server/src/models/world/ai/behaviors/tanner.ts
server/src/models/world/ai/crazedtonwin.ts
server/src/models/world/ai/dedlaenescort.ts
server/src/models/world/ai/default.ts
server/src/models/world/ai/insaneranata.ts

- Added lodash types
- Deadly Dirge won't waste attacks on dead people
- Fix steal helper (maybe? I didn't test it, but I can't see how the previous code would of worked either)
- Fix bug in Dispel helper

add lodash types

---

server/src/helpers/data/GroundManager.ts

Fixes #168
Items that are identical will stack.

stacks items with same mod

---

server/src/helpers/data/GroundManager.ts

Stacks change messed up saving grounds, this should fix it

fix saving multi stack

---

server/src/models/world/ai/behaviors/furupgrader.ts

Fur upgrader should tie and also not bypass upgrade material level reqs

Fur upgrader ties and merges reqs

---

package.json
shared/functions/__tests__/direction.ts
shared/functions/direction.ts
shared/interfaces/direction.ts
shared/jest.config.js
shared/package-lock.json
shared/package.json
shared/tsconfig.json

- Added jest testing to shared
- Added test for all the directions.ts stuff
- Improved/fixed some directions.ts stuff based on testing

Add shared direction tests

---

client/src/app/containers/game-container/map/phaserstates/logic.ts
shared/functions/__tests__/direction.ts
shared/functions/direction.ts
shared/functions/position.ts
shared/functions/sprite.ts
shared/interfaces/direction.ts

- Make more sprite functions use direction
- Make generic terrain direction logic
- Refactor gold to use generic terrain logic

Refactor sprite logic

---

client/src/app/containers/game-container/map/phaserstates/logic.ts
shared/functions/__tests__/position.ts
shared/functions/direction.ts
shared/functions/position.ts

Made a new FOV for the client.
It has a different set of pros, and cons. It probably has bugs.
I have some ideas for a 3.0, but I don't plan on making one yet. I think it would need to know more about walls, and doors, and I would need to build something that can cut the dark FOV in more ways.

Client FOV 2.0

---

client/src/app/containers/game-container/map/phaserstates/logic.ts
client/src/app/pipelines/OutlinePipeline.ts

Improves doors:
- Doors are no longer missing pieces
- Some parts of the door are above you
- Doors outline correctly more often
- Doors have better performance

Make doors awesome
